### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kayobianco** [metagenome-atlas/virome_atlas#1]
Hi,

I am trying to use Virome_atlas but I am getting the following error message: 

(atlasenv) archaea@ArchaeaLMR:~/Downloads/virome_atlas-master$ /home/archaea/Downloads/virome_atlas-master/virome_atlas /media/archaea/UBUNTU-HD/Illumina/Plasmidona/doutorado/DW/atlas /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database -j 4
Building DAG of jobs...
Creating conda environment /home/archaea/Downloads/virome_atlas-master/rules/../envs/vibrant.yaml...
Downloading and installing remote packages.
Environment for ../../../../../../../../home/archaea/Downloads/virome_atlas-master/envs/vibrant.yaml created (location: ../../../../Databases/atlas_database/conda_envs/ff69f220448ad4b1c809bc6bc46e8d9e)
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                 count    min threads    max threads
----------------  -------  -------------  -------------
all                     1              1              1
download_vibrant        1              1              1
run_vibrant             1              4              4
total                   3              1              4

Select jobs to execute...

[Thu Nov 11 22:49:50 2021]
localrule download_vibrant:
    output: /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/VIBRANT/downloaded_vibrant_data
    jobid: 2
    resources: tmpdir=/tmp, mem=70, time=8

Downloading VIBRANT databases to /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/ff69f220448ad4b1c809bc6bc46e8d9e/share/vibrant-1.2.0...

This script will download, extract subsets and press HMM profiles for VIBRANT.
This process will require ~20GB of temporary free storage space, but the final size requirement is ~11GB in the form of pressed HMM databases.
Please be patient. This only needs to be run once and will take a few minutes.
Logger started. Check log file for messages and errors.
VIBRANT Error: see log for details.
VIBRANT databases are downloaded successfully. Please see log file for any error messages.
Touching output file /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/VIBRANT/downloaded_vibrant_data.
[Thu Nov 11 23:10:58 2021]
Finished job 2.
1 of 3 steps (33%) done
Select jobs to execute...

[Thu Nov 11 23:10:58 2021]
rule run_vibrant:
    input: DW/DW_contigs.fasta, /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/VIBRANT/downloaded_vibrant_data
    output: DW/Viruses
    jobid: 1
    wildcards: sample=DW
    threads: 4
    resources: tmpdir=/tmp, mem=70, time=8

Activating conda environment: /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/ff69f220448ad4b1c809bc6bc46e8d9e
split: número inválido de linhas: “0”: Resultado numérico fora de alcance
mv: não foi possível obter estado de 'DW/Viruses/DW_contigs.parallel-runs_*': Arquivo ou diretório inexistente
ls: não foi possível acessar 'DW/Viruses/DW_contigs.parallel-runs_*.txt': Arquivo ou diretório inexistente
Traceback (most recent call last):
  File "/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/ff69f220448ad4b1c809bc6bc46e8d9e/bin/VIBRANT_run.py", line 211, in <module>
    parallels_shell = subprocess.check_output(parallels, shell=True)
  File "/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/ff69f220448ad4b1c809bc6bc46e8d9e/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/ff69f220448ad4b1c809bc6bc46e8d9e/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ls DW/Viruses/DW_contigs.parallel-runs_*.txt' returned non-zero exit status 2.
[Thu Nov 11 23:11:01 2021]
Error in rule run_vibrant:
    jobid: 1
    output: DW/Viruses
    conda-env: /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/ff69f220448ad4b1c809bc6bc46e8d9e
    shell:
        VIBRANT_run.py -i DW/DW_contigs.fasta -t 4 -folder DW/Viruses  -l 1000 -o 4 -no_plot
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job run_vibrant since they might be corrupted:
DW/Viruses
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /media/archaea/UBUNTU-HD/Illumina/Plasmidona/doutorado/DW/atlas/.snakemake/log/2021-11-11T224910.183691.snakemake.log
Traceback (most recent call last):
  File "/media/archaea/UBUNTU-HD/miniconda3/envs/atlasenv/bin/snakemake", line 10, in <module>
    sys.exit(main())

Can you help me?
  File "/media/archaea/UBUNTU-HD/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/__init__.py", line 2738, in main
    success = snakemake(
  File "/media/archaea/UBUNTU-HD/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/__init__.py", line 798, in snakemake
    os.chdir(olddir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/archaea/Downloads/virome_atlas-master'
Traceback (most recent call last):
  File "/home/archaea/Downloads/virome_atlas-master/virome_atlas", line 12, in <module>
  File "/media/archaea/UBUNTU-HD/miniconda3/envs/atlasenv/lib/python3.8/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'snakemake --config database_dir=/media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database -d /media/archaea/UBUNTU-HD/Illumina/Plasmidona/doutorado/DW/atlas --use-conda --conda-prefix /media/archaea/UBUNTU-HD/Illumina/Databases/atlas_database/conda_envs/ -j 4' returned non-zero exit status 1.

**Comment by SilasK** [comment]
Do you understand what this means? 

split: número inválido de linhas: “0”: Resultado numérico fora de alcance
mv: não foi possível obter estado de 'DW/Viruses/DW_contigs.parallel-runs_': Arquivo ou diretório inexistente
ls: não foi possível acessar 'DW/Viruses/DW_contigs.parallel-runs_.txt': Arquivo ou diretório inexistente

**Comment by kayobianco** [comment]
Hi @SilasK,

Sorry, the language of my computer is in Portuguese.

split: invalid number of lines: “0”: Numeric result out of range
mv: unable to get status of 'DW/Viruses/DW_contigs.parallel-runs_': File or directory does not exist
ls: unable to access 'DW/Viruses/DW_contigs.parallel-runs_.txt': File or directory does not exist
